"""Security report generation module."""
import os
import datetime
import json

def generate_report(title, findings, ai_insights=None, output_format="markdown"):
    """Generate a security report in the specified format."""
    now = datetime.datetime.now()
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")
    report_name = f"report_{now.strftime('%Y%m%d_%H%M%S')}"

    if output_format == "markdown":
        return _generate_markdown(title, findings, ai_insights, timestamp, report_name)
    elif output_format == "html":
        return _generate_html(title, findings, ai_insights, timestamp, report_name)
    elif output_format == "json":
        return _generate_json(title, findings, ai_insights, timestamp, report_name)
    else:
        print(f"Unknown format: {output_format}")
        return None

def _generate_markdown(title, findings, ai_insights, timestamp, report_name):
    filename = f"{report_name}.md"
    lines = [
        f"# {title}",
        f"**Generated:** {timestamp}",
        f"**Tool:** Mythos Lab Cyber Toolbox",
        "",
        "---",
        "",
        "## Summary",
        "",
    ]
    if findings:
        for category, items in findings.items():
            lines.append(f"### {category}")
            if isinstance(items, list):
                for item in items:
                    lines.append(f"- {item}")
            else:
                lines.append(str(items))
            lines.append("")
    else:
        lines.append("No findings recorded.")
        lines.append("")

    if ai_insights:
        lines.extend([
            "## AI-Powered Insights",
            "",
            ai_insights,
            "",
        ])

    lines.extend([
        "---",
        "",
        "## Disclaimer",
        "This report was generated by the Mythos Lab Cyber Toolbox for authorized security testing only.",
        "Always obtain proper authorization before conducting security assessments.",
    ])

    content = "\n".join(lines)
    with open(filename, 'w') as f:
        f.write(content)
    print(f"Report saved: {filename}")
    return filename

def _generate_html(title, findings, ai_insights, timestamp, report_name):
    filename = f"{report_name}.html"
    rows = ""
    if findings:
        for category, items in findings.items():
            item_list = ""
            if isinstance(items, list):
                item_list = "".join(f"<li>{i}</li>" for i in items)
            else:
                item_list = f"<li>{items}</li>"
            rows += f"<h3>{category}</h3><ul>{item_list}</ul>"
    else:
        rows = "<p>No findings recorded.</p>"

    ai_section = ""
    if ai_insights:
        ai_section = f"<h2>AI-Powered Insights</h2><pre>{ai_insights}</pre>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
  h1 {{ color: #c0392b; }}
  h2 {{ color: #2c3e50; border-bottom: 2px solid #ecf0f1; }}
  h3 {{ color: #e74c3c; }}
  pre {{ background: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; }}
  .footer {{ font-size: 0.85em; color: #7f8c8d; margin-top: 40px; border-top: 1px solid #ecf0f1; padding-top: 10px; }}
</style>
</head>
<body>
<h1>🔒 {title}</h1>
<p><strong>Generated:</strong> {timestamp} | <strong>Tool:</strong> Mythos Lab Cyber Toolbox</p>
<hr>
<h2>Findings</h2>
{rows}
{ai_section}
<div class="footer">
  <p>This report was generated for authorized security testing only. Always obtain proper authorization.</p>
</div>
</body>
</html>"""
    with open(filename, 'w') as f:
        f.write(html)
    print(f"Report saved: {filename}")
    return filename

def _generate_json(title, findings, ai_insights, timestamp, report_name):
    filename = f"{report_name}.json"
    data = {
        "title": title,
        "generated": timestamp,
        "tool": "Mythos Lab Cyber Toolbox",
        "findings": findings,
        "ai_insights": ai_insights,
    }
    with open(filename, 'w') as f:
        json.dump(data, f, indent=2, default=str)
    print(f"Report saved: {filename}")
    return filename

def run(findings=None, ai_agent=None):
    print("\n📄 Report Generator")
    print("-------------------")
    title = input("Report title [Security Assessment Report]: ").strip() or "Security Assessment Report"
    print("Format:")
    print("  1. Markdown")
    print("  2. HTML")
    print("  3. JSON")
    fmt_choice = input("Select format [1]: ").strip() or "1"
    formats = {"1": "markdown", "2": "html", "3": "json"}
    fmt = formats.get(fmt_choice, "markdown")

    if findings is None:
        findings = {}
        print("\nEnter findings (leave blank to skip a category):")
        for category in ["Critical", "High", "Medium", "Low"]:
            items_input = input(f"  {category} findings (comma-separated): ").strip()
            if items_input:
                findings[category] = [i.strip() for i in items_input.split(",")]

    ai_insights = None
    if ai_agent and findings:
        use_ai = input("\nGenerate AI insights? (yes/no) [no]: ").strip().lower()
        if use_ai in ("yes", "y"):
            summary = json.dumps(findings, default=str)
            print("Generating AI insights...")
            ai_insights = ai_agent.generate_report_insights(summary)

    generate_report(title, findings, ai_insights, fmt)
